
server:
  port: 8081
  shutdown: graceful
spring:
  main:
    # bean???
    lazy-initialization: true
  lifecycle:
    timeout-per-shutdown-phase: 30s #??????,??30s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    #    ???????????????????????
    url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      &allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      max-lifetime: 60000
dictman:
  primaryKey: id    #默认表主键是解析id
  resultList: data.records #默认data.list

# orm??
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration: 
    map-underscore-to-camel-case: true
    #缓存
    cache-enabled: false
    #配置日志  log-impl:日志实现
    log-impl : org.apache.ibatis.logging.slf4j.Slf4jImpl
    # sql-explain-type: AGGREGATE
  global-config:
    banner: false #?????LOGO
    db-config:
      logic-delete-field: deleted # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 2 # ??????(??? 0)
      idType: ASSIGN_UUID #????????,????ASSIGN_ID,??long??id ,ASSIGN_UUID
      tablePrefix: null #????
# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


